### ISSUE TITLE
Deploy on a different PC (Heroku)

### ISSUE THREAD

**Issue by dolanmiu** [DaftMonk/generator-angular-fullstack#1029]
This sounds stupid, or may have been answered, but I couldn't find any results when I search.

How would I deploy on a different PC on Heroku?

The only way I can think of is to delete the old app on Heroku, and re-deploy, otherwise, it would complain saying the name of the app is already taken.

Please help!

**Comment by mariostesla** [comment]
this is the script i am using on Codeship
```
echo "Host heroku.com" >> ~/.ssh/config
echo "   StrictHostKeyChecking no" >> ~/.ssh/config
echo "   CheckHostIP no" >> ~/.ssh/config
echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
mkdir dist && cd dist && git init
yes | heroku keys:add
heroku git:remote --ssh-git -a appName
git pull heroku master && cd ../ && grunt build
yes | grunt buildcontrol:heroku
heroku keys:clear
```
This is for a temporary VM,  for your scenario some of these commands might not be needed (ssh configs, heroku keys) and others are needed only the first time (git init, heroku git:remote)

**Comment by jeshuamaxey** [comment]
This is taken from a `contributing.md` I wrote for a project using this generator. It assumes you've downloaded heroku toolbelt and logged into heroku through their CLI. Perhaps similar instructions should be included into a generated `contributed.md` if one makes it's way into the generator (as discussed in https://github.com/DaftMonk/generator-angular-fullstack/issues/1005).

After cloning the repo run `npm install && bower install` from the project root to install all project dependencies. Next, clone the current version of the production app into `/dist` (which isn't tracked by the repo) from the heroku remote. This is so that when you come to deploy, `/dist` has the correct git configurations. Grunt will overwrite all the contents of `/dist` except for the `/.git` directory when we build the app before deploy.

````
# assuming your heroku domain is my-heroku-app.herokuapp.com
git clone git@heroku.com:my-heroku-app.git dist
````

**Comment by dolanmiu** [comment]
Works, but I had to do a few other things:

https://stackoverflow.com/questions/18406721/heroku-does-not-appear-to-be-a-git-repository

https://stackoverflow.com/questions/4269922/permission-denied-publickey-when-deploying-heroku-code-fatal-the-remote-end?page=1&tab=votes#tab-top

Thank you!!
