### ISSUE TITLE
How can I update my project with the new 'generator-angular-fullstack' version?

### ISSUE THREAD

**Issue by AleksMeshkov** [DaftMonk/generator-angular-fullstack#1048]
Hey!

I have a project created within 'generator-angular-fullstack'  several months ago.
I see that you do regular commits/fixes to this generator. 
So how can I update my current project? 

Thanks in advance.

**Comment by Awk34** [comment]
Because of the way all this works (running the generator to create a new fresh start), the only real way to update a project that was created with an older version is to run the generator again and manually copy over the new code that you want. There's no real way to update a project that was created with the generator before automatically without potentially breaking everything.

Also note: the version on NPM hasn't been updated in quite some time. If you'd like to run the most recent version, clone this repo, and run `npm link` from within it's root. You can then do a `yo angular-fullstack` as normal with the new code.

**Comment by AleksMeshkov** [comment]
@Awk34 Thanks!
