### ISSUE TITLE
Boot Timeout errors when deploying with 2.1.0 to Heroku

### ISSUE THREAD

**Issue by leesharma** [DaftMonk/generator-angular-fullstack#1071]
I tried to deploy a scaffolded app (with 2.1.0) to Heroku, but I am getting boot timeout errors. The old release (2.0.13) doesn't have this issue, so I'd guess that some configuration change in the new release is causing it.

To reproduce this, I ran the following commands (and selected default options):

```bash
mkdir test-app && cd test-app
yo angular-fullstack
bower install && npm install
git init && git add -A && git commit -m 'Initialize repository'
yo angular-fullstack:heroku
cd dist && heroku config:set NODE_ENV=production && heroku addons:create mongolab && heroku ps:scale web=1
grunt --force && grunt buildcontrol:heroku
```

The Heroku logs are as follows, starting with the mongolab attachment:

```
heroku[api]: Attach MONGOLAB resource by <email>
heroku[api]: Release v5 created by <email>
heroku[web.1]: State changed from crashed to starting
heroku[web.1]: Starting process with command `node server/app.js`
app[web.1]: Recommending WEB_CONCURRENCY=1
app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
app[web.1]: Express server listening on 46443, in production mode
heroku[api]: Scale to web=1 by <email>
heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
heroku[web.1]: Stopping process with SIGKILL
heroku[web.1]: Process exited with status 137
heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=secret-hamlet-5547.herokuapp.com request_id=c38e6147-8ec5-4774-8b5a-9e17b69a82ab fwd="69.70.177.123" dyno= connect= service= status=503 bytes=
heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=secret-hamlet-5547.herokuapp.com request_id=9fb59a80-b45a-4dbe-9857-0458ba04dc84 fwd="69.70.177.123" dyno= connect= service= status=503 bytes=
```

Grunt can serve the app locally with no problems.

Let me know if any other information would be useful (or if this is a user error)!

**Comment by georgeportillo** [comment]
+ 1!

**Comment by georgeportillo** [comment]
There's definitely something wrong with this version. I did a restore to version 2.0.13 and deployed to Heroku. Everything worked just fine.

**Comment by Awk34** [comment]
I'd start by just looking at the commits between those two releases

**Comment by RobAikins** [comment]
+1

**Comment by kingcody** [comment]
In `server/config/environment/index.js` change:
```javascript
ip: process.env.IP || 'localhost',
```
to:
```javascript
ip: process.env.IP || '0.0.0.0',
```

**Comment by leesharma** [comment]
Awesome, thanks! That fixed the issue for me.

**Comment by jonchenn** [comment]
Good job, this fixed my problem too!

**Comment by aki-s** [comment]
This worked well for Heroku, but failed to boot on localhost on the contrary though...

**Comment by kingcody** [comment]
@aki-s what is your setup? Also did you receive any errors?

**Comment by aki-s** [comment]
Oh I'm very sorry for bothering you.
I'm newbie to node.js and generator-anular-fullstack.
It turned out nothing problem was there.
 $grunt serve            # Took c.a. 30sec to boot.
 $grunt serve:debug  # Took c.a. 5 min to boot! 
It took too long time to boot, so I thought something wrong with the setting.

**Comment by egkozlov** [comment]
I created my app using angular-fullstack(4.0.4) about 3 weeks ago and wanted to deploy it to heroku. But after deploy I always get "Error R10 (Boot timeout)" error. I spent half of my day and finally figured out that problem was in ../server/config/environment/production.js file. 

`port: process.env.OPENSHIFT_NODEJS_PORT
    || process.env.port
    || 8080,`

process.env.port should be in uppercase: process.env.PORT. I found a commit(https://github.com/angular-fullstack/generator-angular-fullstack/commit/44dccba6091a9b5d362e342c61cf81dfda4c7298) that fixed this problem but unfortunately it was after my app creating :( 
So if you have timeout problem with heroku check your production.js file

**Comment by Awk34** [comment]
@egkozlov that issue has been fixed. Please wait for the next generator release.
