### ISSUE TITLE
Can not deploy to Heroku

### ISSUE THREAD

**Issue by mkoosej** [DaftMonk/generator-angular-fullstack#1105]
I ported my node.js project using angular-fullstack generator and after that when I deploy to Heroku , I get a Boot Time out error https://devcenter.heroku.com/articles/error-codes#r10-boot-timeout. It happens after the express, logs the listen event to console.
I also tested it with Vanilla project generated using the generator and faced the same issue. I added the Mongolab add-on both of cases. 
Although it works fine with your demo project but it has a different packages.json and I think the issue arise form there. So I believe it's not my codes problem and there's some regression in the generator itself.

Anyone experienced the same issue?

**Comment by kingcody** [comment]
Hi @mkoosej, I believe that this is a similar issue to: https://github.com/DaftMonk/generator-angular-fullstack/issues/1071

Which is fixed by applying: https://github.com/DaftMonk/generator-angular-fullstack/pull/1080

The master branch should be pushed to npm soon; but feel free to make the change yourself in the mean time, as it is an easy one.

**Comment by mkoosej** [comment]
Thanks, Cody. I thought that might be the IP problem cause I did the same fix when I deployed it to a VPS but wasn't sure it causes issue in Heroku too. I will give a try.
