### ISSUE TITLE
Feature Request: UI-Bootstrap & Angular Material

### ISSUE THREAD

**Issue by verrol** [DaftMonk/generator-angular-fullstack#1112]
Please consider adding Angular Material from https://material.angularjs.org as an option in the generator prompt. Thus the user can choose just as the for Less/SaaS, etc.

Thanks,

.v

**Comment by softBarbarian** [comment]
Strongly agree !!!

**Comment by remicastaing** [comment]
Has somebody already use Angular Material in conjonction with uiRouter? I'm not sure, they work well together.

**Comment by chinnichaitanya** [comment]
@remicastaing I have a **generator-fullstack** app with *Angular Material* using *ui-router*. They work perfectly well. I got a few dependency issues with *ui-bootstrap* and *Angular Material*. Removing *ui-bootstrap* dependency solved the issue.

**Comment by softBarbarian** [comment]
@remicastaing that is great to hear! Will you be able to contribute to this repo?

**Comment by DanMMX** [comment]
or at least show your set up @chinnichaitanya

**Comment by chinnichaitanya** [comment]
@softBarbarian Yes I'm willing to contribute. Busy with something else as of now. 
@DanMMX Can you tell me what should I show ? As of now, it is not hosted. I can post the link after I host it.

**Comment by verrol** [comment]
@DanMMX If you are just looking for a simple example, then I should be able to do that and share the step and/or code. I haven't tried Angular Material with fullstack, but I have with other generators. I don't see why it wouldn't work.

**Comment by DanMMX** [comment]
Actually not searching for a "simple" example as on blogs or even the Angular Material site @verrol @chinnichaitanya , it's because I tried to put Angular Material on AFS but not sure if it was about configurations or some files missing to add (I removed every front end framework but Angular to make it like the Angular Material site says), or maybe the code I wasn't using correctly but I couldn't make it to add it to AFS.

I'm using AFS because it makes very easy everything and fastens my development, wouldn't quit AFS just to use Angular Material since it's not a requirement for my project, but would look nicer tho, but spent more than 2 hrs trying to make it work and since it wasn't trivial for me I quit at it.

What I'm searching is a commit or two having Bootstrap / Angular UI removed and adding Angular Material on AFS.

**Comment by Awk34** [comment]
Closing in favor of #999

**Comment by verrol** [comment]
@DanMMX FYI, I got AngularJS Material UI to work in the most recent fullstack without issue. 

Sample code  on github [here](https://github.com/verrol/fullstack-demo-ngmaterial), but steps below:

1. create project
   * make sure it is running with 'grunt serve'
2. bower install angular-material --save
3. stop grunt if it was running (this is important)
  * the index.html page won't get updated automatically if you don't
4. start project using 'grunt serve'
   * if you look at the client/index.html file, you should see 4 lines added: angular-material.css, angular-animate.js, angular-aria.js, and angular-material.js
5. edit client/app/app.js
  * added module dependency on **both** 'ngAnimate' and 'ngMaterial'
6. add some directives to your html page, for example on client/app/main/main.html
  *  &lt;md-button class="md-raised"&gt; Raised Button &lt;/md-button&gt;
  * &lt;md-slider ng-model="color" min="5" max="500"&gt;&lt;/md-slider&gt;
