### ISSUE TITLE
Setting configurations in a single command

### ISSUE THREAD

**Issue by RickyGeek** [DaftMonk/generator-angular-fullstack#1130]
Is it possibile to specify all the Configuration (Client and Server) running a single line of command ?

I am trying with this : ```(echo 1; echo n; echo 1; echo 1; echo 1; echo Y; echo n; echo Y) | yo angular-fullstack```

It works fine for the Client Configuration but not for the Server Configuration.

**Comment by Awk34** [comment]
Whenever you run the generator, it creates a `.yo-rc.json` file with the configuration that you used in it. If you then run the generator again with that `.yo-rc.json` file in the working directory, Yeoman will see it and ask if you want to use that config instead of running through every option again. If you provide that file with the config you want, the only thing you have to type is a single `y`. Does this help?

**Comment by RickyGeek** [comment]
Yes, I used that file to automatically generate other yeoman angular-fullstack app automatically running the command ```echo Y | yo angular-fullstack```.
Thank you

**Comment by Awk34** [comment]
Awesome.
