### ISSUE TITLE
how to add facebook outh after starting project without facebook outh

### ISSUE THREAD

**Issue by raza2022** [DaftMonk/generator-angular-fullstack#1139]
am on running project build with angular full stack but not add facebook login at the time of initialize. now am want to add facebook login. is there any way (means command) to add facebook login automatically in my project?. or i have to manually add facebook login?

**Comment by kingcody** [comment]
A little of both actually. Did you generate the project with an authentication boilerplate and any oauth providers?

**Comment by raza2022** [comment]
no actually i need only local oauth at start. But now client need facebook login.am just want to know is there any specific way (one or two command to add FB login) or i have to add it manually.
thanks in advance

**Comment by raza2022** [comment]
if you mean any oauth, then yes am using local oauth initialized by generator

**Comment by kingcody** [comment]
Well the local auth is not actually oauth spec (that would be: Facebook, Google, or Twitter). You can run the generator again, but it will try to overwrite any file that is different. Whether that be because it is adding the code for an oauth provider (like Facebook) or because you changed the code from its original state. What version of the generator are you using?

**Comment by raza2022** [comment]
till now am added facebook login manually. but got error Invalid App ID: id,despite am added client id and secret in config

**Comment by kingcody** [comment]
Without any code/trace its going to be hard to help.

**Comment by kingcody** [comment]
@raza2022 any updates?

**Comment by raza2022** [comment]
solved! i am missing authTypes in user model
thankz
