### ISSUE TITLE
How to upgrade my website seamlessly?

### ISSUE THREAD

**Issue by chenweiyj** [DaftMonk/generator-angular-fullstack#1185]
Because this full stack framework cannot deploy `dist/` directory, each time I am going to upgrade my website, I should run `grunt build` on the server. However my server is a little bit slow, at the moment, users cannot access my website. I want to show a message to tell users my website is upgrading. 

I am using `nginx` as the proxy server and using `pm2` to run the node server as a daemon service.

**Comment by Awk34** [comment]
I'll start by asking: why do you think the generator can't create a deployable `dist` folder?

**Comment by chenweiyj** [comment]
You mean that we can deploy 'dist' folder directly? Because each time 'grunt' is run, the dist folder will be removed and regenerated, I guess we cannot deploy it directly. Am I wrong?

**Comment by amejiarosario** [comment]
Usually, you generate the `dist` folder on your development environment and then copy the `dist` to your server.

**Comment by chenweiyj** [comment]
I use bitbucket deploy key to deploy my website. Do you mean I should add the `dist/` folder to git repository?

**Comment by kingcody** [comment]
You could also create a separate repo just for production releases (`dist/`).

**Comment by Awk34** [comment]
Once you have run `grunt build`, you should be able to run `node dist/server` or `node dist/server/app.js` to run the built code.

**Comment by Ectsang** [comment]
@chenweiyj 

You can set up your remote server like so: https://gist.github.com/Ectsang/e7d5b4fb621d84137052

Then you can use this deploy script: https://gist.github.com/Ectsang/434112457c9d8c25e30a

Notes:
  - To deploy just run `./deploy`
  - Each deploy is tagged by date time
  - Git post-receive hook on the server side detects a new push to your repo and grabs the entire dist/ folder into your webroot
  - Restarts PM2 (you can modify the script so that you only restart your own app)

Let me know if you need the script for a multi-site deploy (e.g. deploying to staging server vs production). Cheers!
