### ISSUE TITLE
The Api JSON is open

### ISSUE THREAD

**Issue by IgorDePaula** [DaftMonk/generator-angular-fullstack#1204]
With or not CORS enabled, or configured to own domain, the api json is open for anyone read. I believe that the api should be open only for the own domain, without external reading it.

**Comment by Awk34** [comment]
It's hard to understand what you're trying to say, but I think you're either trying to say that CORS is enabled by default or that the API can be accessed from different domains. CORS isn't enabled by default, and there's no reason to disallow domains from accessing API endpoints by default.

**Comment by IgorDePaula** [comment]
It's bad text interpretation. I said that with CORS disabled I get read data from api, if I access http://url/api/categories, I read all data, it's normal?

**Comment by kingcody** [comment]
@IgorDePaula I would say that, yes it is that way by design. There are several ways that you can restrict your API access. [**`server/api/user/index.js`**](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/server/api/user%28auth%29/index.js) has two examples:
```javascript
router.get('/', auth.hasRole('admin'), controller.index);
```
and
```javascript
router.get('/me', auth.isAuthenticated(), controller.me);
```

Both examples use methods of [**`server/auth/auth.service.js`**](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/server/auth%28auth%29/auth.service.js).

**Comment by IgorDePaula** [comment]
Thank you, I'll try.

2015-08-27 15:52 GMT-03:00 Cody Mize <notifications@github.com>:

**Comment by IgorDePaula** [comment]
It's works, thank you very much.

2015-08-27 15:55 GMT-03:00 principe.borodin@gmail.com <
principe.borodin@gmail.com>:
