### ISSUE TITLE
Duplicate 'thing' socket and route created by generator with bad path

### ISSUE THREAD

**Issue by stuarthallows** [DaftMonk/generator-angular-fullstack#1205]
I ran the generator taking all defaults except for selecting LESS rather than SASS. There are two problems with the generated code.

In `routes.js` the routes generated are;
```
  app.use('/api/things', require('./api\thing'));
  app.use('/api/things', require('./api/thing'));
  app.use('/api/users', require('./api/user'));
```

and in `socketio.js` the sockets registered are;
```
  require('..\api\thing\thing.socket').register(socket);
  require('../api/thing/thing.socket').register(socket);
```

That is two *thing* entries, one with the slash reversed.

I'm running Windows 10, generator v3.0.0-rc4, npm 2.7.4 and node v0.12.2. I've tried cleaning all caches and reinstalling the generator.

**Comment by kingcody** [comment]
The problem are two problems here actually.

* The project comes with a `app.use('/api/things', require('./api/thing'));` route but also inserts one when generating the `thing` endpoint on initial creation. This problem isn't apparent until the generated route is different than the one that was already included.

Which brings us to our next problem:
* We're using the `path` module to find the relative path from the `routes.js` and `socketio.js` to the required file. However the path modules is using windows style slashes as the route is being generated on a windows machine. 

Since the generated route is different than the included one, it actually gets added; where as normally it would see it as a duplicate and skip the insertion.

**Comment by kingcody** [comment]
@stuarthallows I've submitted two patches (#1206, #1214) to the [canary](https://github.com/DaftMonk/generator-angular-fullstack/tree/canary) branch that should address the issues here. Would you mind testing those and confirm whether or not they do indeed solve your issues?

**Comment by Awk34** [comment]
As Cody mentioned, those patches should fix your problems. Re-open if they persist.
