### ISSUE TITLE
[Poll] Languages/Transpilers supported for generated front-end

### ISSUE THREAD

**Issue by Awk34** [DaftMonk/generator-angular-fullstack#1281]
This is a call-to-action to the community. We would like to know which languages the users of the generator wish to use.

Options:
* JavaScript (ES5 compatible)
* JavaScript (ES latest)
* JavaScript w/ Babel
* JavaScript w/ Traceur
* TypeScript
* CoffeeScript

The reason that this comes up, is because as more and more developers move to using more modern language features and compilers, there becomes more of a desire to switch the generator's code base to transpilers that allow for more modern language features and other options.

There is a desire to drop Vanilla JS and CoffeeScript as supported languages, and move to using transpiles which support modern language features, namely Babel, Traceur, and TypeScript. The desire for this, first of all, is because of the important features that these newer transpilers support. Another reason for this desire is because of the dependence of Angular 2 on newer JS features, such as classes, inheritance, decorators, etc. We would like to transition the front-end code-base to more modern Angular coding standards. The more and more we move to using newer language features and modern Angular practices, the easier it will be to start using Angular 2, convert older Angular 1.x applications into Angular 2 applications, or even maybe using Angular 2 with the generator in the future.

The reason that this comes up, is that we do not want to attempt to support two very different types of languages for the front-end code. From the point of forking, the original code and newer transpiler-supported code would become more and more different, and thus harder and harder to maintain and support.

Please feel free to comment with which languages/compilers you would like to see supported in the future, and perhaps any arguments. Your feedback will impact the future of this generator. Thanks, all!

**Comment by DanMMX** [comment]
Currently there's a work on Gulp, would like to see also a Webpack implementation.

**Comment by corporationsruleyourmom** [comment]
Have you looked at [ngUpgrade](https://github.com/angular/ngUpgrade)? Maybe implementing that would help ease the transition to Angular 2. Also the Angular [blog](http://angularjs.blogspot.ca/2015/08/angular-1-and-angular-2-coexistence.html) talks about upgrading too. This ES6 stuff... It's hard to say this early I haven't seen too many real-world examples... Still looking into Babel and TypeScript...

**Comment by khwerhahn** [comment]
I think this is a good call. The Angular team does encourage TypeScript for a lot of very good reasons. I think the wisest decision would be to follow their lead and focus on TypeScript only, at least for now until this project is ng2 only.

I think it would also be easier to maintain this project.

**Comment by Awk34** [comment]
Pulling in some more contributors: @btford @passy @DaftMonk @kingcody @eddiemonge @sindresorhus @JaKXz @remicastaing @robinboehm

**Comment by passy** [comment]
I agree with @khwerhahn. Angular is officially moving to TypeScript. I don't think it would be a good idea to add another language option to the mix if the decision has already been made upstream.

**Comment by sindresorhus** [comment]
I think TypeScript would make the most sense.

**Comment by Koslun** [comment]
Think TypeScript is definitely the way to go. Babel otherwise.

TypeScript aims to be a superset of all javascript versions, as seen in this table: http://kangax.github.io/compat-table/es6/. Though it is evident that Babel has more ES6 features and many ES7 features I think the features TypeScript brings to the table with optional and propagating typing is more valuable. Enabling a better IDE experience with refactoring and auto-completion. Also possibly better minification (Angular team reduced size of sample 2k LoC by about 20% using Type information to infer variables see [Angular Weekly Notes](https://docs.google.com/document/d/150lerb1LmNLuau_a_EznPV1I1UHMTbEl61t4hZ7ZpS0/edit)).

Even if you don't like the typing in TypeScript it's still optional, and so is most of the ES6 features. The main difference seems to be the class orientation, but with Angular 2 it seems to make a lot of sense to use classes. Non-ES6 or TypeScript more or less have to write boilerplate code to pretend to use classes in Angular 2 either way.

So would agree that TypeScript being the best practice from the Angular team it would make a lot of sense to use it. 

If people for some reason end up hating TypeScript a lot it shouldn't be too hard to shift to Babel either way.

**Comment by remicastaing** [comment]
Nothing to add. @Koslun made a good sum up.
