### ISSUE TITLE
local.env.js does not work on heroku

### ISSUE THREAD

**Issue by dolanmiu** [DaftMonk/generator-angular-fullstack#1334]
My local.env.js works locally

...BUT when I deploy it on Heroku, it seems to be missing, so all my API keys, secrets etc are missing, so my website won't work live!

Here is a screen shot of my ```dist``` directory:

![image](https://cloud.githubusercontent.com/assets/2917613/10033027/b23d84ec-617e-11e5-9096-fa085a9e978f.png)

**Comment by Awk34** [comment]
That's because Git is set to ignore that file: https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/_.gitignore#L8

If it didn't ignore that file, anyone with read rights to your repository would also know all of your API keys!

Either make a similar file on the server, or put the keys into environment variables (`NODE_ENV=production node server`) like the good Lord intended.

**Comment by dolanmiu** [comment]
Thank you for the reply! Learnt something new from this
