### ISSUE TITLE
Microservices

### ISSUE THREAD

**Issue by urosjarc** [DaftMonk/generator-angular-fullstack#1363]
With the rise of microservices it would be good idea to add [seneca.js](http://senecajs.org/) option beside express.js. This lib and the microservic arhitecture itself looks promising.

What are your view on this, is this worth of anyones time?

**Comment by Koslun** [comment]
Think Express.js is a very big part of this generator. Maybe even bigger than the Angular.js part. More or less everything also depends on things that uses Express.js. So to state the obvious, labour-wise, it would be a massive time commitment.

I would much prefer focus on getting the features and fixes already proposed for 3.0 to 3.2 done. At the current pace it's a very non-trivial amount of work to manage, would expect at least all of this year. Additionally I think Angular 2 is likely releasing it's Beta next week at Angular Connect, or soon after. So might be worth actually adopting Angular 2 to the generator by the time 3.2 is out.

Further think it makes more sense to make a new generator specifically aimed at creating microservices. Because I figure the architecture and thinking is different enough to probably be worth it.

So I would personally advocate to push this a bit further into the future or split it into its own generator, but I don't even contribute atm. Maybe there is someone who both really wants this and is willing to contribute.

**Comment by Awk34** [comment]
I agree with @Koslun . I think micro-services are out of the scope of this project, at least for the time being. If you want to get a microservices piece of the generator working, probably a sub-generator, I'd be open to investigating putting it into the generator, but for now I'll close the issue, as to not pull attention away from more pressing issues. Thanks for the suggestion.
