### ISSUE TITLE
Question: How upgrade angular-fullstack

### ISSUE THREAD

**Issue by ajmarmar** [DaftMonk/generator-angular-fullstack#1463]
Hi,

How to upgrade angular-fullstack?, Now DaftMonk has released a new version V3, and in few day He released three corrections version, and I would like to know how to update the project without having to install new versions.

Regards.

**Comment by Awk34** [comment]
Because of the purpose of Yeoman generators, especially in this instance, it isn't practical to try to update an existing project to what's included by a newer app generation. Your best options are to: generate a new project, look at the commit history since the version of the generator that you used, or generate a new project and directly compare it with your current one.
