### ISSUE TITLE
grunt build generates nothing but blank page 

### ISSUE THREAD

**Issue by programming-kid** [DaftMonk/generator-angular-fullstack#614]
Hey @DaftMonk  i started working on one of  my project when v2.0.1 release way back in july now i am finished with it so when ran ```grunt build``` it built my priject successfully but i get blank page in browser without error . but when i serve in development using ```grunt server``` it works fine.

I really don't undestand whats wrong , node-inspector seems to hang i really dont know how to debug this issue.

pls help

thanks

**Comment by amaalzohny** [comment]
hi guys , i  have the same issue reported from @programming-kid , once i run " grunt serve:dist" , i am getting the same error , 
any suggsetion or solution ?

**Comment by Koslun** [comment]
@amaalzohny This issue is so old I would recommend creating a new issue with more details about your project and re-posting exactly what error you are seeing. Not completely sure I know what error you are referring to and filling in the table that's created when you create a new issue helps narrow any potential bug down a lot.
