### ISSUE TITLE
Any plans for es6 and traceur support?

### ISSUE THREAD

**Issue by agnislav** [DaftMonk/generator-angular-fullstack#684]
Hi guys,

Is there a plan to include traceur support to the generator? It would be nice to play with ES6 today to be ready for angular 2.0.

Sincerely,

Agnislav.

**Comment by JaKXz** [comment]
It would be cool to leverage [Babel](https://babeljs.io/) and just start using ES 2015 / 2016 features already.

**Comment by Awk34** [comment]
It would be nice to be able to use some of the features of ES6, but AFAIK using Traceur/etc with this generator would involve changing a lot of code to be ES6 compatible

**Comment by thejameskyle** [comment]
Hi, Babel contributor here. ES6 is actually pretty easy to get started with, it's completely backwards compatible so anything you previously wrote will continue to work, and you can start migrating features one by one and because Babel generates simple high-quality output you don't need to be locked into it forever like you would with Traceur.

If you need any help setting up or using Babel let me know or stop by our support chat: https://gitter.im/babel/babel
