### ISSUE TITLE
Angular fullstack and ionic framework

### ISSUE THREAD

**Issue by nschurmann** [DaftMonk/generator-angular-fullstack#739]
Hey guys, has anybody tried to use this amazing generator with the ionic framework?, i'm having issues configuring it and it would be awesome to use this generator with ionic framework for animations, transitions and also native look&feel.

**Comment by tejasmanohar** [comment]
Doesn't quite make sense. This generates a backend, too. Use `ionic create`

**Comment by nschurmann** [comment]
Of course makes sense, ionic framework doesn't have generators for controllers, services, etc. Also the structure of ionic is very poor compared to fullstack angular generator.

**Comment by tejasmanohar** [comment]
@nschurmann 1 small flaw in what you're saying -- this is angular-*fullstack* - Ionic is for HTML5 mobile applications, that's the front end only.

**Comment by nschurmann** [comment]
@tejasmanohar it seems that you forgot that you can use only the frontend of angular-fullstack apps. And you can also only use the backend. And you can also use both, please stop arguing if it makes sense or not. I need help using them together and not a mentorship about if it should be done or if should not.

**Comment by andrewstuart** [comment]
This generator is forked from generator-angular, which would support your use case much better if you want an angular-specific generator.

I've personally used it for a phonegap-based angular application deployed on IOS, so I know that it's possible.  I really don't think it's worth the trouble and customization you'll need to go through trying to use generator-angular-fullstack to work with a purely client-side app. Generator-angular is much better for this case as it has grunt tasks oriented toward deploying an optimized, minified app.

Another option is `generator-ionic`, though I've never used it so I can't comment on quality.

**Comment by jasonhargrove** [comment]
@nschurmann was making a fine point. Whether you use all of the features of this generator or not means little. What's means a lot are the patterns. You could argue superiority, or you can accept that everyone has their preferences – but for the most part, the patterns used in generator-angular-fullstack are stronger in my opinion than others. Yes this includes generator-angular, which does not use a components or modular approach. As it stands, I use this generator often, even where fullstack is not needed.

**Comment by smirciat** [comment]
I know this issue is closed, but it does come up second in a Google search for “ionic angular-fullstack” so I thought this might be a reasonable place to share a few thoughts on the subject.  I am assuming I am not the only developer who is a) learning with this generator and b) interested in attaching a mobile front-end to my established angular-fullstack backend.  The process is not as quick and easy as some blogs might have you believe, but it is possible. And in my opinion it’s worth it over the alternative of writing a mobile front-end from scratch after you already put all the work into an angular-fullstack front end.
My web app was generated with version 3.1.1 of the generator, but I’m confident version 4 would have similar results and challenges.  Step one is to create a new ionic app with “ionic start myApp,” then replace the “www” contents with the “client” contents of the angular-fullstack app.  Next, I pointed the api calls to ‘https://my.backend.url + /api/things’ to point the mobile app at my backend.  For some reason, ionic did not like ES6 very much, I tried gulp-babel but it didn’t seem to help any.  So I ended up refactoring some of the generated code, mostly getting rid of Javascript classes and fat arrow functions in favor of older, clunkier structures.  I modified a version of the angular-generator backend with cors functionality and changed CSRF to false to accept requests from the mobile app.  At this point ionic serve was mostly successful in the browser, but I got the infamous white screen of death on the ios emulator.  I tried a lot of ways to view console output, but never succeeded.  I had to get rid of <base href=”/”> in index.html, since the app would not load past that.  Then to determine which modules were not injecting properly, I added:
```
Window.onerror = function(errorMsg,url,lineNumber){
     Alert(‘Error: ‘ + errorMsg.substring(0,800) +  ‘  url: ‘ + url + ‘ line: ‘ + lineNumber);
};
```
to the top of app.js.  This finally made error messages visible in the emulator.  I found some packages that worked after updating them, and the fact that I needed to inject ionic-bundle.js to make it work.  Then I ran it on an actual device and encountered even more errors, but with the onerror script, I was able to see them and address them.  
After all this I now have a reasonable cross-platform mobile front-end that works in parallel with my original web-app front-end.  It uses mostly the same code as my original.  My authentication works with the backend, but I was unable to get Google or Facebook OAuth to work.  There is not a lot of help out there in the Google results to work through these issues, so hopefully this helps someone else.
