### ISSUE TITLE
How to manage hierarchy roles in generator-angular-fullstack?

### ISSUE THREAD

**Issue by maryampashmi** [DaftMonk/generator-angular-fullstack#959]
I have following case where i need to assign hierarchy roles. My roles are admin => superEditor => editor =>user 
1.All of them have access to poll menu except user
2.Admin controllers everything in whole system
3.Super editor can add new editors to system 

To do that i defined polls route for each of them separately.(admin-superEditor-editor)
superEditor is like a siteManager  and admin is like blogManager.So i define blog manager and site manager too. 
All the state in the routes have xxxx.polls format. I don't know how i should implement this case with fullstack.If i need several routes or not? If somebody can give me help to correct my architecture i will be appreciated.

![problem](https://cloud.githubusercontent.com/assets/6945288/7447334/486f413c-f1f7-11e4-98cb-d27682c17c23.jpg)

**Comment by zeatful** [comment]
These can be managed through simple queries in your UI through your controller.  To define the hierarchy you can do this in your server/config/environment/index.js file where you see userRoles: ['guest', 'user', 'admin'].  You simply set the privilege from left(least) to right(highest).  Then when a call is made on the server side for the call hasRole('guest'), a user of role 'user' or 'admin' would also be able to have the same access since they have higher privilege.

I don't believe you need these extra "polls" folders as you have it now.  You may want to write a provider or service for this on your UI side to avoid complicated role checks for every case in every place and just handle it in one place.

**Comment by maryampashmi** [comment]
@zeatful  Yes, I defined roles in server/config/environment/index.js. Polls is one tab which present particular content to the specific set of people. Also only user editor and admin have access to add new user to system. Therefore what's going on with the routing part? where i have to define user management and polls and give the privilege. Do you mean that i don't need to write in in sub folder of admin?

**Comment by Awk34** [comment]
closing as this isn't specific to this generator
