### ISSUE TITLE
Refreshing any page causes Error: ENOENT, stat ... at Error (native) issue

### ISSUE THREAD

**Issue by mcpDESIGNS** [DaftMonk/generator-angular-fullstack#978]
I'm not sure what could be causing this, but somehow it looks like the server is trying to bring up the "client" folder as if it was inside of the "server" folder.

I ran the app like usual, going to the *server* folder, and running **node app** to fire it up.

As an example let's say I refresh the signup page:
http://localhost:9000/signup

Instead of serving up the page, the screen simply says this:
*Error: ENOENT, stat 'c:\NodeApps\FullStackApp\server\client\index.html' at Error (native)*

Notice **\server\client\**

I actually haven't changed anything internally (server or otherwise) yet, I just recently got everything run. Any ideas?

**Comment by chinnichaitanya** [comment]
Try doing it using ```grunt serve```.

**Comment by mcpDESIGNS** [comment]
@chinnichaitanya That did the trick! Thank you!

I'm newer to grunt and such, what's the different with running that and **node app** (app being the name of the .js file). 

**grunt serve** doesn't need the actual name of the server .js file because of this line correct?

nodemon: {
      debug: {
        script: 'server/app.js', // <-----

**Comment by chinnichaitanya** [comment]
@mcpDESIGNS Basically ```grunt serve``` will automatically load all the ```js, html and css``` files in your app into the ```index.html``` file in ```client``` folder. Once the ```index.html``` is populated perfectly, everything will work.

The error you got is mostly because some files are not loaded to render properly. 

Yes ```node app.js``` will also work only when your ```index.html``` is populated properly. So after you run ```grunt serve``` , you can stop it and re-launch it using ```node app.js```. 

So, if you have installed any new modules, you can either include them manually into your ```index.html``` or you can run ```grunt serve```. Then ```node app.js``` will work normally.

I might be wrong though, in the explanation of the process. So please feel free to correct me.

**Comment by mcpDESIGNS** [comment]
Thank you again, yeah it looks fine, strangely `node app` still has the refresh issue, so I suppose I'll just stick with `grunt serve`!

Did you have to set anything up to have the life reload working? At the moment nothing gets restarted when client files .html / .js are changed. Sorry for bothering you!

**Comment by chinnichaitanya** [comment]
I don't think I have set up anything for livereload to work. Try running ```npm install && bower install``` again. 
If that still doesn't work, try updating your installed modules.

Hope that it helps.

**Comment by mcpDESIGNS** [comment]
You rule, everything's working now :) :+1:
